### ISSUE TITLE
🐛 Wrong handling of double backslashes and exponents in math equations

### ISSUE THREAD

**Issue by AndreiBiziuk** [ebullient/obsidian-slides-extended#43]
### Input data (markdown source)

    $$
    \begin{cases}
    2x_1^2 + x_2^{2} \leq 10 \\
    x_1 + 3x_2 \leq 15 \\
    x_1, x_2 \geq 0
    \end{cases}
    $$

### Expected Behavior

Equation correctly displayed in preview and in presentation

### Current behaviour

    $$
    \begin{cases}
    2x_1^2 + x_2^{2} \leq 10 \\
    x_1 + 3x_2 \leq 15 \\
    x_1, x_2 \geq 0
    \end{cases}
    $$

Equation displayed correctly in note preview:

![изображение](https://github.com/user-attachments/assets/de9497f4-dec1-4dec-8a7d-dc608db10448)

but not in presentation:

![изображение](https://github.com/user-attachments/assets/2c71fe94-b559-4676-8800-083eed49e41b)

Note the lack of exponent in (2x_1^2) in first equation

This code displayed correctly in presentation:

    $$
    \begin{cases}
    2x_1^{2} + x_2^{2} \leq 10 \\\\
    x_1 + 3x_2 \leq 15 \\\\
    x_1, x_2 \geq 0
    \end{cases}
    $$

Exponents in curly braces and backslashes are doubled. 
But this is not displaying right in note preview:

![изображение](https://github.com/user-attachments/assets/41d3c151-dd28-4f7c-b0ec-0563fd16c950)

### Steps to reproduce

Create note with provided input data.
Click "Show slide preview"

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version

1.7.4

### Slides Extended Plugin Version

2.1.3

### Checks

- [X] I have tried it in the sandbox vault with only this plugin enabled

### Possible solution

Not treat backslashes in equations as escaping and probably other special characters (e.g. ^)

**Comment by ebullient** [comment]
This may help: https://github.com/ebullient/obsidian-slides-extended/commit/c2bc999cf923e2839e3cea690fec28e2e4f4bdf9

mathjax was.. really borked.. even in Advanced Slides.

hopefully, I've fixed it.

**Comment by AndreiBiziuk** [comment]
Hello. Unfortunately, equations still not rendering correctly in 2.1.11

![Image](https://github.com/user-attachments/assets/d58a4fde-ec6d-4fae-85f1-3cde70560c18)

On the left is the obsidian equation preview, which is correct.

**Comment by ebullient** [comment]
Hey. I'll take the partial win. It is better than it was!

**Comment by AndreiBiziuk** [comment]
Yea )  Newlines working now ) But subscripts broke

**Comment by AndreiBiziuk** [comment]
It worked! Thank you very much!
